name: widget_catalog
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  rxdart: ^0.27.1
  # device_preview: ^0.7.4
  responsive_framework: ^0.1.4
  solid_bottom_sheet: ^0.1.10
  sliding_sheet: ^0.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bloc: ^8.0.2
  flutter_bloc: ^8.0.0
  provider: ^6.0.2
  get: ^4.6.1
  flutter_screenutil: ^5.1.0
  responsive_sizer: ^3.0.5+1
  responsive: ^0.3.11+11
  layout: ^1.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^2.2.0
  fl_chart: ^0.36.1
  flutter_html: ^3.0.0-alpha.2
  flutter_html_table: ^3.0.0-alpha.2
  google_maps_flutter: ^2.1.1
  custom_info_window: ^1.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  widget_with_codeview: ^2.0.1+2
  animations: ^2.0.2
  flutter_staggered_animations: ^1.0.0
  simple_animations: ^4.0.1
  loading_animations: ^2.2.0
  dots_indicator: ^2.1.0
  flutter_slidable: ^1.2.0
  cached_network_image: ^3.2.0
  backdrop: ^0.7.1
  convex_bottom_bar: ^3.0.0
  flutter_riverpod: ^1.0.3
  flutter_native_splash: ^2.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  #color: "#42a5f5"
  #color_dark: "#000000"
  background_image: assets/splash.png
  image: assets/splash.png
  android: true
  ios: true
  web: false
  android12: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - data/
    - assets/
    - assets/icons/
    - assets/images/
    - lib/
    - lib/src/
    - lib/src/pages/
    - lib/src/widgets/
    - lib/src/pages/catalog/
    - lib/src/pages/catalog/layout_pages/
    - lib/src/pages/catalog/drawer_menu_pages/
    - lib/src/pages/catalog/Bottom_sheet_pages/
    - lib/src/pages/catalog/Button_pages/
    - lib/src/pages/catalog/text_pages/
    - lib/src/pages/catalog/animation_pages/
    - lib/src/pages/catalog/pageview_pages/
    - lib/src/pages/catalog/responsive_pages/
    - lib/src/pages/catalog/table_pages/
    - lib/src/pages/catalog/async_pages/
    - lib/src/pages/catalog/clipper_pages/
    - lib/src/pages/catalog/information_pages/
    - lib/src/pages/catalog/gestures_pages/
    - lib/src/pages/catalog/image_pages/
    - lib/src/pages/catalog/lists_pages/
    - lib/src/pages/catalog/appbar_pages/
    - lib/src/pages/catalog/tabs_pages/
    - lib/src/pages/integrations/inherited_pages/
    - lib/src/pages/integrations/riverpood_pages/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
